### PR TITLE
Fix NeuronPopulation class issue

### PR DESCRIPTION
**Pull request by filimarc**
When NeuronPopulation obj is created it needs a model, so we fix when is called in __getitem__

### CODE REVIEW

**Review by Helveg — COMMENTED** [review]
When/where is this information needed? I don't see it being accessed anywhere. If it's going to be used externally, add it to the `NeuronPopulation`'s  public API with a getter property. I think I never added this because the neuron population is stored in a dict with the model as keys, but it's fine to add this.

**Review by danilobenozzo — COMMENTED** [review]
```
Traceback (most recent call last):
  File "/home/neuro_sim1/neuron/cerebellum/test_GrC_circuit.py", line 16, in <module>
    sim = network.run_simulation("neurontest")
  File "/home/neuro_sim1/neuron/bsb-core/bsb/profiling.py", line 159, in decorated
    return f(*args, **kwargs)
  File "/home/neuro_sim1/neuron/bsb-core/bsb/core.py", line 443, in run_simulation
    return adapter.simulate(simulation)[0]
  File "/home/neuro_sim1/neuron/bsb-core/bsb/simulation/adapter.py", line 76, in simulate
    data = self.prepare(simulation)
  File "/home/neuro_sim1/neuron/bsb-neuron/bsb_neuron/adapter.py", line 90, in prepare
    self.create_devices(simulation)
  File "/home/neuro_sim1/neuron/bsb-neuron/bsb_neuron/adapter.py", line 157, in create_devices
    device_model.implement(self, simulation, simdata)
  File "/home/neuro_sim1/neuron/bsb-neuron/bsb_neuron/devices/voltage_recorder.py", line 11, in implement
    for model, pop in self.targetting.get_targets(
  File "/home/neuro_sim1/neuron/bsb-core/bsb/simulation/targetting.py", line 92, in wrapper
    return self.satisfy_fractions(f(self, *args, **kwargs))
  File "/home/neuro_sim1/neuron/bsb-core/bsb/simulation/targetting.py", line 225, in get_targets
    return {
  File "/home/neuro_sim1/neuron/bsb-core/bsb/simulation/targetting.py", line 226, in <dictcomp>
    model: simdata.populations[model][
  File "/home/neuro_sim1/neuron/bsb-neuron/bsb_neuron/adapter.py", line 250, in __getitem__
    return NeuronPopulation([p for p, b in zip(self, item) if b])
TypeError: NeuronPopulation.__init__() missing 1 required positional argument: 'instances' 
```
@Helveg this was the error when running the simulation part

**Comment by Helveg** [comment]
@danilobenozzo That seems rather impossible if you were using the official versions of the software involved. How could `NeuronPopulation` ever be missing arguments, and how could introducing a **_new breaking change_** ever be the solution to this **_existing_** problem? That seems anachronistic ;p

**Comment by danilobenozzo** [comment]
> How could `NeuronPopulation` ever be missing arguments,

since `def __init__(self, model: "NeuronCell", instances: list):`
is it enough just passing the list as in https://github.com/dbbs-lab/bsb-neuron/blob/4fc632ce1e8306d07a351b34cb1fbd30222742a3/bsb_neuron/adapter.py#L250
?
shouldn't rather be `return NeuronPopulation(self._model, [p for p, b in zip(self, item) if b])`
?
or only `return [p for p, b in zip(self, item) if b]`

**Review by Helveg — APPROVED** [review]

**Comment by Helveg** [comment]
You are right :) I didn't see that the constructor had 2 arguments :)

**Pull request merged**
